apiVersion: apps/v1
kind: Deployment
metadata:
  name: chart-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chart-proxy
  template:
    metadata:
      labels:
        app: chart-proxy
    spec:
      # Make mounted volumes group-writable by GID 1000 so UID 1000 can write
      securityContext:
        fsGroup: 1000
      initContainers:
        # chart-fetcher pulls charts from registries based on config
        - name: chart-fetcher
          image: ghcr.io/michielvha/chart-fetcher:latest
          imagePullPolicy: Always
          command: ["/usr/local/bin/chart-fetcher"]
          args:
            - "--config=/config/config.yaml"
            - "--outputPath=/charts"
          env:
            - name: HOME
              value: /home/app
            # Add any registry credentials as environment variables
            - name: REG1_USERNAME
              valueFrom:
                secretKeyRef:
                  name: registry-credentials
                  key: username
                  optional: true
            - name: REG1_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: registry-credentials
                  key: password
                  optional: true
          workingDir: /charts
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: charts
              mountPath: /charts
            - name: tmp
              mountPath: /tmp
        - name: helm-repo-index
          # Generate Helm repo index for the pulled charts
          image: alpine/helm:3.17.2
          command: ["sh", "-c", "helm repo index /usr/share/nginx/html --url http://localhost"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: charts
              mountPath: /usr/share/nginx/html
            - name: tmp
              mountPath: /tmp
      containers:
        # Nginx serves the charts as a Helm repository
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: charts
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: chartfetch-config
        - name: charts
          emptyDir: {}
        - name: tmp
          emptyDir:
            medium: Memory
        - name: nginx-config
          configMap:
            name: nginx-config