project_name: chart-fetcher
version: 2

builds:
  - env:
      # goreleaser does not work with CGO, it could also complicate
      # usage by users in CI/CD systems like Terraform Cloud where
      # they are unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
#    no_unique_dist_dir: true # we need unique dist dirs to build multi-arch docker images
    binary: '{{ .ProjectName }}' # _v{{ .Version }} # DONE: Decide if we want to keep the _v there instead of just _, pipeline needs to be adjusted if changed
snapshot:
  version_template: '{{ incpatch .Version }}'
archives:
  - formats:
    - zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this is a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate it's not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  draft: false
changelog:
  use: git
  filters:
    include:
      - "^feat:"
      - "^fix:"
      - "^chore:"
      - "^docs:"
  sort: asc # Sort commits chronologically (oldest to newest)
  groups:   # organize your changelog into categories using regular expressions, start commit with feat: or fix:
    - title: "🚀 Features"
      regexp: "^.*?feat(\\([\\w]+\\))?!?:.+$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^.*?fix(\\([\\w]+\\))?!?:.+$"
      order: 1
    - title: "🛠 Maintenance"
      regexp: "^.*?chore(\\([\\w]+\\))?!?:.+$"
      order: 2

# To check deprecations:
# https://goreleaser.com/deprecations/
