registries:
  - url: "quay.io/kannika/charts"
    is_oci: true
    charts:
      - name: "kannika"
        version: "0.9.1"
  - url: "https://engiebnlms.jfrog.io/artifactory/api/helm/prd-helm-virtual"
    username_env: "REG1_USERNAME"
    password_env: "REG1_PASSWORD"
    charts:
      - name: "autopass"
        version: "0.1.0"
  - url: "https://engiebnlms.jfrog.io/artifactory/api/helm/prd-helm-external-secrets"
    username_env: "REG1_USERNAME"
    password_env: "REG1_PASSWORD"
    charts:
      - name: "external-secrets"
        version: "0.10.7"
