apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: nginx-config
    files:
      - config/default.conf
  - name: chartfetch-config
    files:
      - config/config.yaml
