# This configuration file defines multiple Helm chart registries to fetch charts from.
# It is provided as a sensible default and can be customized / overwritten by providing
# your own configuration file (see README for details).
registries:
  # Public Registries
  - url: "quay.io/kannika/charts"
    is_oci: true
    charts:
      - name: "kannika"
        version: "0.9.1"
  # # Private Registries (requires credentials to be set in environment variables)
  # - url: "https://jfrog.io/artifactory/api/helm/external-secrets"
  #   username_env: "REG1_USERNAME"
  #   password_env: "REG1_PASSWORD"
  #   charts:
  #     - name: "external-secrets"
  #       version: "0.10.7"